# Generated by Django 3.0.5 on 2021-11-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211105_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='count',
            new_name='amount',
        ),
    ]
